### ISSUE TITLE
SetHostsFile update logic deletes host file contents

### ISSUE THREAD

**Issue by leshkinski** [rsWinAutomationSupport/rsboot#11]
Current logic within the SetHostsFile script resource will overwrite any hosts file data that is not part of the initial get-content filter set.

It also references '$nodeinfo.PullServerIP' and '$nodeinfo.PullServerName' values, which no longer exist in $nodeinfo...

https://github.com/rsWinAutomationSupport/rsboot/blob/wmf4_namefix/boot.ps1#L476-L482

**Comment by jonathan-madison** [comment]
https://github.com/rsWinAutomationSupport/rsboot/blob/wmf4_namefix/boot.ps1#L24-L46

They are set in this function. PullServerName always exists, it is either set to the name put in as PullServerAddress or the name discovered as the certificate CN when an IP is used for PullServerAddress. If PullServerAddress is an IP, PullServerIP is also set to the same value.

Not being included in nodeinfo.json has been fixed by: https://github.com/rsWinAutomationSupport/rsboot/blob/wmf4_namefix/boot.ps1#L24-L46

The HOSTS logic is using the -notmatch filter, meaning the only HOSTS info overwritten is any line actually matching PullServerName or PullServerIP.

It's also important to point out this script should only be run on new servers, so replacing HOSTS information should not be an issue regardless.
